/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.isamm.Galarie;

import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Application extends javax.swing.JFrame {

    /**
     * Creates new form Application
     */
    GalerieDao gestionGalerie = new GalerieDao();
    DefaultTableModel model = new DefaultTableModel();
    Galerie galiere = new Galerie();
    int taillep=0;
    int tailles=0;
    public Application() {
        initComponents();
        
            model.addColumn("nom");
                model.addColumn("date");
    model.addColumn("theme");

    model.addColumn("prix");
    model.addColumn("vendue");
    model.addColumn("Type");
    
    table.setModel(model);
    
        //afficher();
            
                


                
		/*System.out.println("---------------------------------------    travail avec mongodb    -----------------------------------");
		GalerieDao gestionGalerie = new GalerieDao();
		gestionGalerie.createGalerieMongoDB(galiere);
//		gestionGalerie.findGalerieNomOrganisateurMongoDB(galiere, "Seif allah medini5");
		gestionGalerie.updateGalerieNomOrganisateurMongoDB(galiere, "Seif allah medini5" ,"seifallahmedini-updated-test-2");
//		gestionGalerie.findGalerieNomOrganisateurMongoDB(galiere, "seifallahmedini-updated-test-2");
//		gestionGalerie.deleteGalerieNomOrganisateurMongoDB(galiere, "seifallahmedini-updated-test-2");
		List<DBObject> oeuvres=  gestionGalerie.findOeuvreTypeGalerieMongoDB(galiere, "seifallahmedini-updated-test-2", "peinture");
		System.out.println(oeuvres);
//		gestionGalerie.findOeuvreNomGalerieMongoDB(galiere, "sculpture1", "seifallahmedini-updated-test-2");
		//gestionGalerie.findOeuvrePrixGalerieMongoDB(galiere, 1500, 2550, "seifallahmedini-updated-test-2");
*/	
    }
    

    
    private void inserer(){
try {
    model.setRowCount(0);
  
 for(int i=0;i<taillep;i++)
   {
        String nom=(String) galiere.getPeintures()[i].getNom();
        String date=(String) galiere.getPeintures()[i].getDate_creation();
        String theme=(String) galiere.getPeintures()[i].getTheme();
        double prix=(double) galiere.getPeintures()[i].getPrix();
        if( galiere.getPeintures()[i].isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Peinture"}); 
        else
            model.addRow(new Object[]{nom,date,theme,prix,"Non","Peinture"});  
        
   }
 
  for(int i=0;i<tailles;i++)
   {
        String nom=(String) galiere.getSculptures()[i].getNom();
        String date=(String) galiere.getSculptures()[i].getDate_creation();
        String theme=(String) galiere.getSculptures()[i].getTheme();
        double prix=(double) galiere.getSculptures()[i].getPrix();
        if( galiere.getSculptures()[i].isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Sculpture"});  
        else
            model.addRow(new Object[]{nom,date,theme,prix,"Non","Sculpture"});  
   }
}catch(Exception e){System.err.println(e);}

table.setModel(model);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tmTxt = new javax.swing.JTextField();
        nomTxt = new javax.swing.JTextField();
        matTxt = new javax.swing.JTextField();
        dateTxt = new javax.swing.JTextField();
        prixTxt = new javax.swing.JTextField();
        tailleTxt = new javax.swing.JTextField();
        volTxt = new javax.swing.JTextField();
        poidTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        nvRad = new javax.swing.JRadioButton();
        vRad = new javax.swing.JRadioButton();
        sculRad = new javax.swing.JRadioButton();
        peintRad = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        addBtn2 = new javax.swing.JButton();
        addBtn3 = new javax.swing.JButton();
        addBtn4 = new javax.swing.JButton();
        adrTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        orgTxt = new javax.swing.JTextField();
        maxTxt = new javax.swing.JTextField();
        minTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Nom  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 50, 90, 15);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 90, 15);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Théme :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 90, 15);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Prix :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 200, 90, 15);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Vendu : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 90, 15);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("Matières utilisés : ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 580, 130, 20);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("Taille :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 390, 60, 15);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("Volume :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 450, 80, 15);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel11.setText("Poids :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 510, 110, 20);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("Type :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 310, 90, 15);
        getContentPane().add(tmTxt);
        tmTxt.setBounds(180, 140, 130, 30);
        getContentPane().add(nomTxt);
        nomTxt.setBounds(180, 40, 130, 30);

        matTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matTxtActionPerformed(evt);
            }
        });
        getContentPane().add(matTxt);
        matTxt.setBounds(180, 580, 130, 30);
        getContentPane().add(dateTxt);
        dateTxt.setBounds(180, 90, 130, 30);
        getContentPane().add(prixTxt);
        prixTxt.setBounds(180, 190, 130, 30);
        getContentPane().add(tailleTxt);
        tailleTxt.setBounds(180, 380, 130, 30);
        getContentPane().add(volTxt);
        volTxt.setBounds(180, 440, 130, 30);
        getContentPane().add(poidTxt);
        poidTxt.setBounds(180, 510, 130, 30);

        jLabel12.setText("Organisateur :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 450, 110, 30);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Date", "Theme", "Prix", "Vendu", "Type"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 40, 700, 400);

        nvRad.setText("Oui");
        getContentPane().add(nvRad);
        nvRad.setBounds(260, 250, 93, 23);

        vRad.setText("Non");
        vRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vRadActionPerformed(evt);
            }
        });
        getContentPane().add(vRad);
        vRad.setBounds(180, 250, 45, 23);

        sculRad.setText("Sculpture");
        getContentPane().add(sculRad);
        sculRad.setBounds(180, 340, 93, 23);

        peintRad.setText("Peinture");
        getContentPane().add(peintRad);
        peintRad.setBounds(180, 310, 90, 23);

        addBtn.setText("Afficher Les sculptures");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(1050, 520, 180, 40);

        addBtn1.setText("Filtrer par prix entre");
        addBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn1);
        addBtn1.setBounds(840, 600, 180, 40);

        addBtn2.setText("Afficher Les peintures");
        addBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn2);
        addBtn2.setBounds(840, 520, 180, 40);

        addBtn3.setText("Ajouter");
        addBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn3);
        addBtn3.setBounds(670, 520, 130, 40);

        addBtn4.setText("Chercher");
        addBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn4);
        addBtn4.setBounds(670, 600, 130, 40);
        getContentPane().add(adrTxt);
        adrTxt.setBounds(950, 450, 150, 30);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Adresse :");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(880, 450, 110, 30);

        saveBtn.setText("Enregistrer galerie");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(1130, 450, 150, 30);
        getContentPane().add(orgTxt);
        orgTxt.setBounds(690, 450, 140, 30);
        getContentPane().add(maxTxt);
        maxTxt.setBounds(1050, 620, 170, 30);
        getContentPane().add(minTxt);
        minTxt.setBounds(1050, 580, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\GAILLARD_5_rue_chapon.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vRadActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
       		List<DBObject> oeuvres=  gestionGalerie.findOeuvreTypeGalerieMongoDB(orgTxt.getText(), "sculpture");
		try {
    model.setRowCount(0);
  
 for(int i=0;i<oeuvres.size();i++)
   {
       
        DBObject obj = oeuvres.get(i);

        String nom=(String)obj.get("nom");
        String date=(String) obj.get("date_creation");
        String theme=(String) obj.get("theme");
       double prix=Double.parseDouble(oeuvres.get(i).get("prix").toString());
      //double prix=10;
    /*    if( obj.isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Peinture"}); 
        else*/
            model.addRow(new Object[]{nom,date,theme,prix,"non","sculpture"});
   }

}catch(Exception e){JOptionPane.showMessageDialog(null, e.getClass().getName());}

table.setModel(model);
 
    }//GEN-LAST:event_addBtnActionPerformed

    private void addBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn1ActionPerformed
              		List<DBObject> oeuvres=  gestionGalerie.findOeuvrePrixGalerieMongoDB( Double.parseDouble(minTxt.getText()), Double.parseDouble(maxTxt.getText()), orgTxt.getText());
		try {
    model.setRowCount(0);
  
 for(int i=0;i<oeuvres.size();i++)
   {
       
        DBObject obj = oeuvres.get(i);

        String nom=(String)obj.get("nom");
        String date=(String) obj.get("date_creation");
        String theme=(String) obj.get("theme");
       double prix=Double.parseDouble(oeuvres.get(i).get("prix").toString());
      //double prix=10;
    /*    if( obj.isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Peinture"}); 
        else*/
            model.addRow(new Object[]{nom,date,theme,prix,"non","sculpture"});
   }

}catch(Exception e){JOptionPane.showMessageDialog(null, e.getClass().getName());}

table.setModel(model);
 
    }//GEN-LAST:event_addBtn1ActionPerformed

    private void addBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn3ActionPerformed
       
		Peinture peinture1 = null;
                Sculpture sculpture1 = null;
                if(peintRad.isSelected())
                {
                     peinture1 = new Peinture(nomTxt.getText(),dateTxt.getText(), tmTxt.getText(), Float.parseFloat(prixTxt.getText()), false, "seif", Double.parseDouble(tailleTxt.getText()));
                galiere.ajouterPeinture(peinture1);
                                taillep++;
                }
                     
                 else
                {
                    sculpture1 = new Sculpture(nomTxt.getText(), dateTxt.getText(), tmTxt.getText(), Float.parseFloat(prixTxt.getText()), false, "ghaith", Double.parseDouble(volTxt.getText()), Double.parseDouble(poidTxt.getText()),
				matTxt.getText());
                    tailles++;
		
		
		galiere.ajouterSculpture(sculpture1);
                }
                inserer();
    }//GEN-LAST:event_addBtn3ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       galiere.setNom_organisateur(orgTxt.getText());
       galiere.setAdresse(adrTxt.getText());
	gestionGalerie.createGalerieMongoDB(galiere);
        JOptionPane.showMessageDialog(null, "Galerie ajouté !");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void matTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matTxtActionPerformed

    private void addBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn2ActionPerformed
     		List<DBObject> oeuvres=  gestionGalerie.findOeuvreTypeGalerieMongoDB( orgTxt.getText(), "peinture");
		try {
    model.setRowCount(0);
  
 for(int i=0;i<oeuvres.size();i++)
   {
       
        DBObject obj = oeuvres.get(i);

        String nom=(String)obj.get("nom");
        String date=(String) obj.get("date_creation");
        String theme=(String) obj.get("theme");
       double prix=Double.parseDouble(oeuvres.get(i).get("prix").toString());
      //double prix=10;
    /*    if( obj.isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Peinture"}); 
        else*/
            model.addRow(new Object[]{nom,date,theme,prix,"non","peinture"});
   }

}catch(Exception e){JOptionPane.showMessageDialog(null, e.getClass().getName());}

table.setModel(model);
    }//GEN-LAST:event_addBtn2ActionPerformed

    private void addBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn4ActionPerformed
          		List<DBObject> oeuvres = null;
        try {
            oeuvres = gestionGalerie.findOeuvreNomGalerieMongoDB( nomTxt.getText(), orgTxt.getText());
        } catch (NotExistException ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        }
		try {
    model.setRowCount(0);
  
 for(int i=0;i<oeuvres.size();i++)
   {
       
        DBObject obj = oeuvres.get(i);

        String nom=(String)obj.get("nom");
        String date=(String) obj.get("date_creation");
        String theme=(String) obj.get("theme");
       double prix=Double.parseDouble(oeuvres.get(i).get("prix").toString());
      //double prix=10;
    /*    if( obj.isVendue())
            model.addRow(new Object[]{nom,date,theme,prix,"Oui","Peinture"}); 
        else*/
            model.addRow(new Object[]{nom,date,theme,prix,"non","peinture"});
   }

}catch(Exception e){JOptionPane.showMessageDialog(null, e.getClass().getName());}

table.setModel(model);
    }//GEN-LAST:event_addBtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton addBtn2;
    private javax.swing.JButton addBtn3;
    private javax.swing.JButton addBtn4;
    private javax.swing.JTextField adrTxt;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField matTxt;
    private javax.swing.JTextField maxTxt;
    private javax.swing.JTextField minTxt;
    private javax.swing.JTextField nomTxt;
    private javax.swing.JRadioButton nvRad;
    private javax.swing.JTextField orgTxt;
    private javax.swing.JRadioButton peintRad;
    private javax.swing.JTextField poidTxt;
    private javax.swing.JTextField prixTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JRadioButton sculRad;
    private javax.swing.JTable table;
    private javax.swing.JTextField tailleTxt;
    private javax.swing.JTextField tmTxt;
    private javax.swing.JRadioButton vRad;
    private javax.swing.JTextField volTxt;
    // End of variables declaration//GEN-END:variables
}
